///////////////////////////////////////////////////////////
//  IngredientListRecord.cs
//  Implementation of the Class IngredientListRecord
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////

using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    public class IngredientListRecord
    {

        public string Note;
        public Product Product;
        public float Quantity;
        public float Value;
        public Product m_Product;

        public IngredientListRecord()
        {

        }

        ~IngredientListRecord()
        {

        }

        public virtual void Dispose()
        {

        }

        public INutrientProfile GetNutrientProfile()
        {

            return null;
        }

    }//end IngredientListRecord
}

