///////////////////////////////////////////////////////////
//  INutrientProfile.cs
//  Implementation of the Class INutrientProfile
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////

using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    /// <summary>
    /// This interface contains the basic mandatory nutrients, that should describe a
    /// product-relative object.
    /// The idea is to use this interface as a parent type, whenever there is need to
    /// develop a more detailed nutrient-type class (f. ex. different classes will have
    /// to be used for supplements, vitamins etc.)
    /// </summary>
    public class INutrientProfile
    {

        public float Carbohydrates;
        public float Fat;
        public ushort PerGrams = 100;
        public float Protein;
        public Product m_Product;

        public INutrientProfile()
        {

        }

        ~INutrientProfile()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end INutrientProfile
}

