///////////////////////////////////////////////////////////
//  ISaleAvailableProduct.cs
//  Implementation of the Interface ISaleAvailableProduct
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////

using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    public interface ISaleAvailableProduct
    {

    }//end ISaleAvailableProduct
}


