///////////////////////////////////////////////////////////
//  Meal.cs
//  Implementation of the Class Meal
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////

using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    public class Meal
    {

        public string Description;
        public int Images;
        public IngredientList Ingrediens;

        public Meal()
        {

        }

        ~Meal()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end Meal
}
