///////////////////////////////////////////////////////////
//  MealDistribution.cs
//  Implementation of the Class MealDistribution
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////

using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    public class MealDistribution
    {

        public Meal m_Meal;

        public MealDistribution()
        {

        }

        ~MealDistribution()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end MealDistribution
}

