///////////////////////////////////////////////////////////
//  Product.cs
//  Implementation of the Class Product
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////


using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    public class Product
    {

        public int Images;
        public string Name;
        public INutrientProfile Nutrients;
        public float Price;
        public UnitOfMeasure UnitOfMeasure;
        public Unit m_Unit;

        public Product()
        {

        }

        ~Product()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end Product
}

