///////////////////////////////////////////////////////////
//  Unit.cs
//  Implementation of the Class Unit
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////


using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    public class Unit
    {

        public UnitOfMeasure Measure;
        public WrappingType WrappingType;

        public Unit()
        {

        }

        ~Unit()
        {

        }

        public virtual void Dispose()
        {

        }

    }//end Unit
}

