///////////////////////////////////////////////////////////
//  WrappingType.cs
//  Implementation of the Class WrappingType
//  Generated by Enterprise Architect
//  Created on:      16-lis-2014 20:18:04
//  Original author: Wojtek
///////////////////////////////////////////////////////////

using Matrix.Dietician;
using System.Collections.Generic;

namespace Matrix.Dietician
{
    public enum WrappingType : int
    {

        Bulk,
        Box,
        Bag,
        Cup
    }//end WrappingType
}
